# Generated by Django 5.0.6 on 2024-05-18 16:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default=api.models.generateCode, max_length=10, unique=True),
        ),
    ]
