# Generated by Django 5.0.6 on 2024-05-18 17:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_home_guest_canpause_remove_home_votes_skip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='host',
        ),
        migrations.AddField(
            model_name='home',
            name='password',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default=api.models.generateCode, help_text='Leave empty if no change needed', max_length=10, unique=True),
        ),
    ]
