# Generated by Django 5.0.6 on 2024-05-18 18:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_home_host_home_password_alter_home_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='code',
            field=models.CharField(default=api.models.generateCode, max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='home',
            name='mistakes',
            field=models.IntegerField(default=6, verbose_name='Erros'),
        ),
        migrations.AlterField(
            model_name='home',
            name='password',
            field=models.CharField(default='', max_length=12, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='home',
            name='spaces',
            field=models.BooleanField(default=False, verbose_name='Permitir espaços'),
        ),
        migrations.AlterField(
            model_name='home',
            name='tips',
            field=models.BooleanField(default=True, verbose_name='Permitir dicas'),
        ),
    ]
